### ISSUE TITLE
'Secrets' deprecation

### ISSUE THREAD

**Issue by ChefAustin** [ericgeldmacher/nbcli#40]
Not sure if this project is still maintained or not but figured I'd open this issue just in case...

[Secrets functionality has been removed](https://docs.netbox.dev/en/stable/release-notes/version-3.0/#breaking-changes:~:text=The%20secrets%20functionality%20present%20in%20prior%20releases%20of%20NetBox%20has%20been%20removed.) from Netbox in v3.0. Might be worth updating `nbcli`'s logic to reflect this change to avoid the following warning (and perhaps other similar-such warnings) from being generated when calling `nbcli search`:
```
$ nbcli search bogus

Vlan
====
VID  Name    Group         Tenant  Status  Role           Description
42   bogus  bogus_vlans  -       Active  bogus_role  -

[WARNING](nbcli.search): No API endpoint found for "secret".
```

**Comment by ericgeldmacher** [comment]
Secret support will be removed in the next version.
Issue created for developing a better strategy for handling support models. #41
